# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 689fc47faf3122bdbde37dda65007c2b6f9b70d98e82aa43078b9b1619069d95f440d1c4ef7bf7c368be645ac792f4ff7633b861e51ca16fe5f6c0db95a00c37

test:
  secret_key_base: 07f8edc5bd104337903a0229fceabfec7f2e418f55384bd65d7628cc93f34eaf3cf922ece8c6959670a52f782136f85b0ac9e3ee324d63502dc841a167d5fd2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
